---
name: publish to npm
on: { push: { tags: ["v*"] }, workflow_dispatch: null }
permissions: { id-token: write, contents: read }
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: { name: npm, url: https://npm.im/github-down }
    steps: [
      uses: actions/checkout@v7,
      uses: kjanat/runner@master,
      uses: oven-sh/setup-bun@v2,
      run: runner install --frozen --kill-on-fail publish:npm,
    ]
